# -*- coding: utf-8 -*-
"""박세인test3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uq8QmGUA65MWopZNVtHdJEafA7D8Mqjn
"""

alphabet=input()
result= "대문자" if alphabet.isupper() else "소문자"
print(f"당신이 입력한 문자{alphabet}은 {result}입니다")