# -*- coding: utf-8 -*-
"""박세인test2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o6sckyR5puSquaMXINhSF6VtzJfLV5Ob
"""

total=용돈=10000
거스름돈=용돈-3550*1
print("거스름돈",":",거스름돈,"원")
ch1=거스름돈//500
ch2=(거스름돈-ch1*500)//100
ch3=(거스름돈-ch1*500-ch2*100)//50
print("500원 짜리 거스름돈 : ",ch1, "개", sep="")
print("100원 짜리 거스름돈 : ",ch2, "개", sep="")
print("50원 짜리 거스름돈 : ",ch3, "개", sep="")